Fix release script and changelog date
The executable name was changed and so the script need to be changed as
well

diff --git a/.github/workflows/nightly_snapshot.yaml b/.github/workflows/nightly_snapshot.yaml
--- a/.github/workflows/nightly_snapshot.yaml
+++ b/.github/workflows/nightly_snapshot.yaml
@@ -612,19 +612,19 @@ jobs:
               env:
                    RELEASE_INPUT: ${{ github.event.inputs.release }}
               run: |
+                  version=$(echo artifacts/Slint-cpp-*-win64-MSVC-AMD64.exe | sed -nre 's/^.*-([0-9]+\.[0-9]+\.[0-9]+).*$/\1/p')
+                  if [[ -z "$version" ]]; then
+                    echo "Version not found"
+                    exit 1
+                  fi
+                  major_version=`echo $version | sed -e "s,\([0-9]*\)\.[0-9]*\.[0-9]*,\1,"`
+                  minor_version=`echo $version | sed -e "s,[0-9]*\.\([0-9]*\)\.[0-9]*,\1,"`
                   if [ "$RELEASE_INPUT" != "true" ]; then
                     notes_file=slint-src/docs/nightly-release-notes.md
                     version=nightly
                     download_version=$version
                   else
                     notes_file=slint-src/docs/release-notes.md
-                    version=$(echo artifacts/Slint-cpp-*-win64-MSVC-x86_64.exe | sed -nre 's/^.*-([0-9]+\.[0-9]+\.[0-9]+).*$/\1/p')
-                    if [[ -z "$version" ]]; then
-                      echo "Version not found"
-                      exit 1
-                    fi
-                    major_version=`echo $version | sed -e "s,\([0-9]*\)\.[0-9]*\.[0-9]*,\1,"`
-                    minor_version=`echo $version | sed -e "s,[0-9]*\.\([0-9]*\)\.[0-9]*,\1,"`
                     download_version=v$version
                   fi
                   echo "VERSION=$version" >> $GITHUB_OUTPUT
