VS Code Extension: Exclude developer information from the README published to the VS Code Marketplace

diff --git a/.github/workflows/nightly_snapshot.yaml b/.github/workflows/nightly_snapshot.yaml
--- a/.github/workflows/nightly_snapshot.yaml
+++ b/.github/workflows/nightly_snapshot.yaml
@@ -268,6 +268,13 @@ jobs:
               run: |
                   if [ "$RELEASE_INPUT" != "true" ]; then
                     ../../scripts/prepare_vscode_nightly.sh
+                  else
+                    if grep -q 'lines below this marker are stripped from the release' CMakeLists.txt; then
+                      sed -i '/lines below this marker are stripped from the release/,$ d' README.md
+                    else
+                      echo "Missing strip marker in VS Code Extension README. Either add or fix this script."
+                      exit 1
+                    fi                  
                   fi
             - name: "npm install"
               working-directory: editors/vscode
