Make find_package(Slint) patching more robust for releases
After substituting find_package(Slint) with find_package(Slint $version), verify that we did replace (at least one occurrence).

diff --git a/.github/workflows/nightly_snapshot.yaml b/.github/workflows/nightly_snapshot.yaml
--- a/.github/workflows/nightly_snapshot.yaml
+++ b/.github/workflows/nightly_snapshot.yaml
@@ -553,6 +553,10 @@ jobs:
                 cd slint-cpp-templates-stm32
                 if [ "$RELEASE_INPUT" = "true" ]; then
                     find . -name "CMakeLists.txt" | xargs sed -i "s/find_package(Slint)/find_package(Slint ${{ steps.version.outputs.VERSION }})/g"
+                    if ! grep -q 'find_package(Slint 1\.)' **/CMakeLists.txt; then
+                      echo "Substituting the choice of nightly Slint against the released version failed. Check this script and CMakeLists.txt"
+                      exit 1
+                    fi
                 fi
                 for board in stm32h735g-dk stm32h747i-disco; do
                     mv $board  slint-cpp-template-$board
