esp-idf: Add support for using pre-built binaries
Run the nightly esp-idf test against the esp-idf slint nightly
binaries, after creating them. The snapshot is run earlier as well
then, so that the tests don't "leak" into the morning working hours.

diff --git a/.github/workflows/upload_esp_idf_component.yaml b/.github/workflows/upload_esp_idf_component.yaml
--- a/.github/workflows/upload_esp_idf_component.yaml
+++ b/.github/workflows/upload_esp_idf_component.yaml
@@ -18,6 +18,16 @@ jobs:
         container: espressif/idf:latest
         steps:
             - uses: actions/checkout@v4
+            - name: Remove use of nightly version
+              if: github.event.inputs.release == 'true'
+              working-directory: api/cpp/esp-idf/slint
+              run:
+                if grep -q 'set(SLINT_USE_NIGHTLY_VERSION TRUE)' CMakeLists.txt; then
+                        sed -i '/set(SLINT_USE_NIGHTLY_VERSION TRUE)/d' CMakeLists.txt
+                else
+                    echo "SLINT_USE_NIGHTLY_VERSION marker is missing in CMakeLists.txt. Did you forget to change this script?""
+                    exit 1
+                fi
             - name: Upload component
               if: github.event.inputs.release == 'true'
               uses: espressif/upload-components-ci-action@v1
